name: example
description: A new Jaspr project
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0
  live_cells_core: ^1.4.0

  live_cells_jaspr:
    path: ../

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static

