name: live_cells_jaspr
description: Provides utilities for using the Live Cells library in Jaspr projects.
version: 0.1.0
repository: https://github.com/alex-gutev/live_cells_jaspr
issue_tracker: https://github.com/alex-gutev/live_cells_jaspr/issues

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  live_cells_core: ^1.4.0
  jaspr: ^0.21.7

dev_dependencies:
  jaspr_lints: ^0.5.1
  jaspr_test: ^0.21.7
  lints: ^6.0.0
  mockito: ^5.6.1
  test: ^1.25.6
